
package br.unipar.sistemavenda.panel;

import br.unipar.sistemavenda.dao.ClienteDAO;
import br.unipar.sistemavenda.dao.ClienteDAOImp;
import br.unipar.sistemavenda.model.Cliente;
import br.unipar.sistemavenda.tablemodels.ClienteTableModel;
import br.unipar.sistemavenda.util.EntityManagerUtil;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;


public class PesquisarClientePanel extends javax.swing.JPanel {

   
    private ClienteTableModel model;
    private Cliente cliente;
    private List<Cliente> lista;
    VendaFrame vendaFrame = null;
    
    public PesquisarClientePanel(VendaFrame vendaFrame, String nmCliente) {
        this.vendaFrame = vendaFrame;
        initComponents();  
        atualizarLista(nmCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSelecionar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSelecionar.setText("Selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });
        jPanel1.add(btSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCliente.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane2.setViewportView(jTableCliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        cliente = model.getSelectedItem(jTableCliente, lista);
        getClienteSelecionado();
        SwingUtilities.getWindowAncestor(this).dispose(); 
    }//GEN-LAST:event_btSelecionarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
        System.out.println("Fechar Frame");
    }//GEN-LAST:event_btCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCliente;
    // End of variables declaration//GEN-END:variables

    private void atualizarLista(String nmCliente) {
        lista = new ArrayList<>();
        
        ClienteDAO clienteDao = new ClienteDAOImp(EntityManagerUtil.getMananger());
        
        lista.addAll(clienteDao.findCliente(nmCliente));
        
        model = new ClienteTableModel(lista);

        jTableCliente.setModel(model);
    }
    
    public Cliente getClienteSelecionado(){
        vendaFrame.retornarCliente(cliente);
        return cliente;
    }
}
