package br.unipar.sistemavenda.panel;

import br.unipar.sistemavenda.dao.ClienteDAO;
import br.unipar.sistemavenda.dao.ClienteDAOImp;
import br.unipar.sistemavenda.dao.ProdutoDAO;
import br.unipar.sistemavenda.dao.ProdutoDAOImp;
import br.unipar.sistemavenda.model.Cliente;
import br.unipar.sistemavenda.model.Produto;
import br.unipar.sistemavenda.tablemodels.ProdutoTableModel;
import br.unipar.sistemavenda.util.EntityManagerUtil;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;


public class PesquisarProdutoPanel extends javax.swing.JPanel {

    private VendaFrame vendaFrame = null;
    private Produto produto;
    private ProdutoTableModel model;
    private List<Produto> lista;
    
    public PesquisarProdutoPanel(VendaFrame vendaFrame, String dsProduto) {
        this.vendaFrame = vendaFrame;
        initComponents();
        atualizarLista(dsProduto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProduto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(null);

        btSelecionar.setBackground(new java.awt.Color(0, 255, 0));
        btSelecionar.setText("Selecionar");
        btSelecionar.setToolTipText("");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });
        add(btSelecionar);
        btSelecionar.setBounds(270, 365, 100, 30);

        btCancelar.setBackground(new java.awt.Color(184, 20, 20));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        add(btCancelar);
        btCancelar.setBounds(390, 365, 100, 30);

        jTableProdutos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProdutos.setMaximumSize(new java.awt.Dimension(2147483647, 12257454));
        jTableProdutos.setMinimumSize(new java.awt.Dimension(0, 0));
        jTableProdutos.setPreferredSize(new java.awt.Dimension(500, 400));
        jTableProdutos.setRowHeight(25);
        jScrollPane3.setViewportView(jTableProdutos);

        add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 500, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        produto = model.getSelectedItem(jTableProdutos, lista);
        getProdutoSelecionado();
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btSelecionarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables

    private void atualizarLista(String dsProduto) {
    
        lista = new ArrayList<>();

        ProdutoDAO produtoDao = new ProdutoDAOImp(EntityManagerUtil.getMananger());
        
        lista.addAll(produtoDao.findProduto(dsProduto));
        
        model = new ProdutoTableModel(lista);

        jTableProdutos.setModel(model);
    }

    private Produto getProdutoSelecionado() {
        vendaFrame.retornarProduto(produto);
        return produto;
    }
}
