/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unipar.sistemavenda.panel;

import br.unipar.sistemavenda.Exception.ValidacaoException;
import br.unipar.sistemavenda.dao.ItemVendaDAO;
import br.unipar.sistemavenda.dao.ItemVendaDAOImp;
import br.unipar.sistemavenda.dao.VendaDAO;
import br.unipar.sistemavenda.dao.VendaDAOImp;
import br.unipar.sistemavenda.model.Cliente;
import br.unipar.sistemavenda.model.ItemVenda;
import br.unipar.sistemavenda.model.Produto;
import br.unipar.sistemavenda.model.Venda;
import br.unipar.sistemavenda.panel.PesquisarClientePanel;
import br.unipar.sistemavenda.tablemodels.ItemVendaTableModel;
import br.unipar.sistemavenda.util.EntityManagerUtil;
import jakarta.persistence.EntityManager;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Panel;
import java.awt.event.KeyEvent;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author victo
 */
public class VendaFrame extends javax.swing.JFrame {
    
    ArrayList<ItemVenda> listaProdutos = new ArrayList<>();
    private Cliente cliente;
    private Produto produto;
    JFrame frame; 
    ItemVendaTableModel model;
    
    public VendaFrame() {
        initComponents();
        EntityManagerUtil.getEntityManagerFactory();
        atualizarValorPadrão();
        atualizarListaProdutos();
        setLocationRelativeTo(null);
        //setSize(650, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        tfProduto = new javax.swing.JTextField();
        btAddProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProdutos = new javax.swing.JTable();
        tfQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfValorUnitario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDesconto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfVlrTotalProd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfQtdTotal = new javax.swing.JTextField();
        tfVlrTotal = new javax.swing.JTextField();
        tfVlrDesconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfCliente = new javax.swing.JTextField();
        btFinalizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(660, 520));

        jLabel3.setText("Produto:");

        tfProduto.setBackground(new java.awt.Color(216, 223, 231));
        tfProduto.setPreferredSize(new java.awt.Dimension(200, 25));
        tfProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfProdutoKeyReleased(evt);
            }
        });

        btAddProduto.setBackground(new java.awt.Color(0, 255, 0));
        btAddProduto.setText("Adicionar");
        btAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProdutoActionPerformed(evt);
            }
        });

        JTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTableProdutos);

        tfQtd.setMinimumSize(new java.awt.Dimension(0, 0));
        tfQtd.setName(""); // NOI18N
        tfQtd.setPreferredSize(new java.awt.Dimension(60, 25));
        tfQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfQtdKeyReleased(evt);
            }
        });

        jLabel4.setText("Qtd");

        tfValorUnitario.setMinimumSize(new java.awt.Dimension(0, 0));
        tfValorUnitario.setPreferredSize(new java.awt.Dimension(60, 25));
        tfValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfValorUnitarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValorUnitarioKeyTyped(evt);
            }
        });

        jLabel5.setText("Vlr. Unit");

        tfDesconto.setMinimumSize(new java.awt.Dimension(0, 0));
        tfDesconto.setPreferredSize(new java.awt.Dimension(60, 25));
        tfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDescontoKeyReleased(evt);
            }
        });

        jLabel6.setText("Desc");

        tfVlrTotalProd.setEditable(false);
        tfVlrTotalProd.setBackground(new java.awt.Color(255, 255, 204));
        tfVlrTotalProd.setMinimumSize(new java.awt.Dimension(0, 0));
        tfVlrTotalProd.setPreferredSize(new java.awt.Dimension(60, 25));

        jLabel7.setText("Vlr. Total");

        tfQtdTotal.setEditable(false);
        tfQtdTotal.setBackground(new java.awt.Color(255, 255, 204));
        tfQtdTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdTotalActionPerformed(evt);
            }
        });

        tfVlrTotal.setEditable(false);
        tfVlrTotal.setBackground(new java.awt.Color(255, 255, 204));
        tfVlrTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVlrTotalActionPerformed(evt);
            }
        });

        tfVlrDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVlrDescontoActionPerformed(evt);
            }
        });
        tfVlrDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfVlrDescontoKeyReleased(evt);
            }
        });

        jLabel8.setText("Qtd Total");

        jLabel9.setText("Valor Total");

        jLabel10.setText("Desconto Total");
        jLabel10.setToolTipText("");

        tfCliente.setBackground(new java.awt.Color(216, 223, 231));
        tfCliente.setPreferredSize(new java.awt.Dimension(200, 25));
        tfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfClienteKeyReleased(evt);
            }
        });

        btFinalizar.setBackground(new java.awt.Color(0, 255, 0));
        btFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        btFinalizar.setText("Finalizar");
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente:");

        btRemover.setBackground(new java.awt.Color(246, 46, 22));
        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btCancelar.setBackground(new java.awt.Color(184, 20, 20));
        btCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btRemover)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfQtdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(tfVlrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(tfVlrDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(tfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tfVlrTotalProd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btAddProduto))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVlrTotalProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(btAddProduto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addComponent(tfQtdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(tfVlrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(1, 1, 1)
                        .addComponent(tfVlrDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProdutoActionPerformed
        try {
            validarCamposProduto();
            ItemVenda iv = new ItemVenda();
 
            iv.setDescUnit(Double.parseDouble(tfDesconto.getText()));
            iv.setQtd(Integer.parseInt(tfQtd.getText()));
            iv.setVlUnit(Double.parseDouble(tfValorUnitario.getText()));
            iv.setVlTotal(Double.parseDouble(tfVlrTotalProd.getText()));
            iv.setProduto(produto);

            listaProdutos.add(iv);

            atualizarValorPadrão();
            atualizarCampos();
            atualizarListaProdutos();
        } catch (ValidacaoException ex) {
        }   
    }//GEN-LAST:event_btAddProdutoActionPerformed

    private void tfQtdTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtdTotalActionPerformed

    private void tfVlrTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVlrTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVlrTotalActionPerformed

    private void tfVlrDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVlrDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVlrDescontoActionPerformed

    private void tfClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tfCliente.setText("");
            JPanel clientePanel = new PesquisarClientePanel(this, tfCliente.getText().toLowerCase());
            abrirPanel(clientePanel);
        }
    }//GEN-LAST:event_tfClienteKeyReleased

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        try {
            validarCamposVenda();
            finalizarVenda();
        } catch (ValidacaoException ex) {
        }
    }//GEN-LAST:event_btFinalizarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limparTudo();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tfProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProdutoKeyReleased
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tfProduto.setText("");
            JPanel produtoPanel = new PesquisarProdutoPanel(this, tfProduto.getText().toLowerCase());
            abrirPanel(produtoPanel);
        }
    }//GEN-LAST:event_tfProdutoKeyReleased

    private void tfValorUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorUnitarioKeyTyped
        
    }//GEN-LAST:event_tfValorUnitarioKeyTyped

    private void tfValorUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorUnitarioKeyReleased
        calcularvalorTotalProduto();
    }//GEN-LAST:event_tfValorUnitarioKeyReleased

    private void tfQtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQtdKeyReleased
        calcularvalorTotalProduto();
    }//GEN-LAST:event_tfQtdKeyReleased

    private void tfDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescontoKeyReleased
        calcularvalorTotalProduto();
    }//GEN-LAST:event_tfDescontoKeyReleased

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
       listaProdutos.remove(model.getSelectedItem(JTableProdutos, listaProdutos));
       atualizarListaProdutos();
       atualizarCampos();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void tfVlrDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVlrDescontoKeyReleased
        atualizarDesconto(Double.parseDouble(tfVlrDesconto.getText()));
    }//GEN-LAST:event_tfVlrDescontoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableProdutos;
    private javax.swing.JButton btAddProduto;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFinalizar;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfDesconto;
    private javax.swing.JTextField tfProduto;
    private javax.swing.JTextField tfQtd;
    private javax.swing.JTextField tfQtdTotal;
    private javax.swing.JTextField tfValorUnitario;
    private javax.swing.JTextField tfVlrDesconto;
    private javax.swing.JTextField tfVlrTotal;
    private javax.swing.JTextField tfVlrTotalProd;
    // End of variables declaration//GEN-END:variables

    private void abrirPanel(JPanel panel) {
        frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(panel, BorderLayout.CENTER);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        System.out.println("Abrir panel");
    }

    
    public void retornarCliente(Cliente cliente){
        if(cliente!=null){
            tfCliente.setText(cliente.getNmCliente());
            this.cliente = cliente;
        }
    }
    
    public void retornarProduto(Produto produto){
        if(produto!=null){
            tfProduto.setText(produto.getDescricao());
            this.produto = produto;
        }
    }

    private void calcularvalorTotalProduto() {
            if(tfValorUnitario!=null && tfDesconto!=null && tfQtd!=null){
                String txt = "";
                txt = String.valueOf((Double.parseDouble(tfValorUnitario.getText())*Double.parseDouble(tfQtd.getText()))-Double.parseDouble(tfDesconto.getText()));
                tfVlrTotalProd.setText(txt);
            }
    }

    private void atualizarListaProdutos() {
        model = new ItemVendaTableModel(listaProdutos);
        JTableProdutos.setModel(model);
    }

    private void atualizarCampos() {
        double vlrTotal=0;
        double dscTotal=0;
        int qtdTotal=0;
        
        for(int i = 0; i<listaProdutos.size(); i++){
            vlrTotal += (listaProdutos.get(i).getVlUnit()) * (listaProdutos.get(i).getQtd());
            dscTotal += listaProdutos.get(i).getDescUnit();
            qtdTotal += listaProdutos.get(i).getQtd();
        }

        atualizarDesconto(dscTotal);
        tfQtdTotal.setText(String.valueOf(qtdTotal));
        tfVlrDesconto.setText(String.valueOf(dscTotal));
    }

    private void limparTudo() {
        tfCliente.setText("");
        tfDesconto.setText("0");
        tfProduto.setText("");
        tfQtd.setText("0");
        tfQtdTotal.setText("0");
        tfValorUnitario.setText("0");
        tfVlrDesconto.setText("0");
        tfVlrTotal.setText("0");
        tfVlrTotalProd.setText("0");
        cliente = null;
        produto = null;
        
        listaProdutos.clear();
        atualizarListaProdutos();
    }

    private void finalizarVenda() {
        EntityManager em = EntityManagerUtil.getMananger();
        VendaDAO vendaDAO = new VendaDAOImp(em);
                
        Venda venda = new Venda();
        venda.setCliente(cliente);
        venda.setDescontoTotal(Double.parseDouble(tfVlrDesconto.getText()));
        venda.setQtdItens(Integer.parseInt(tfQtdTotal.getText()));
        venda.setValorTotal(Double.parseDouble(tfVlrTotal.getText()));
        
        venda = vendaDAO.insert(venda);
        
        ItemVendaDAO itemVendaDAO = new ItemVendaDAOImp(em);
        
        for(int i = 0; i<listaProdutos.size(); i++){
            listaProdutos.get(i).setVenda(venda);
            itemVendaDAO.insert(listaProdutos.get(i));
        }
        limparTudo();
        em.close();
    }

    private void validarCamposVenda() throws ValidacaoException {
        if(cliente==null){
            tfCliente.requestFocus();
            JOptionPane.showMessageDialog(null,"Informe o cliente", "Atenção",
                    JOptionPane.WARNING_MESSAGE,null);
            throw new ValidacaoException("Informe um cliente!");
        }
        if(listaProdutos.isEmpty()){
            tfProduto.requestFocus();
            JOptionPane.showMessageDialog(null,"Informe ao menos um produto", "Atenção",
                    JOptionPane.WARNING_MESSAGE,null);
            throw new ValidacaoException("Informe os produtos!");
        }
        
    }

    private void validarCamposProduto() throws ValidacaoException {
        if(produto==null){
            tfProduto.requestFocus();
            JOptionPane.showMessageDialog(null,"Informe um produto", "Atenção",
                    JOptionPane.WARNING_MESSAGE,null);
            throw new ValidacaoException("Informe um produto!");
        }
        if(tfValorUnitario.getText().isBlank() || tfValorUnitario.getText().isEmpty()){
            tfValorUnitario.requestFocus();
            JOptionPane.showMessageDialog(null,"Informe o valor", "Atenção",
                    JOptionPane.WARNING_MESSAGE,null);
            throw new ValidacaoException("Informe um valor unitário!");
        }
        if(tfQtd.getText().isBlank() || tfQtd.getText().isEmpty()){
            tfQtd.requestFocus();
            JOptionPane.showMessageDialog(null,"Informe a Quantidade", "Atenção",
                    JOptionPane.WARNING_MESSAGE,null);
            throw new ValidacaoException("Informe a quantidade!");
        }
        if(tfDesconto.getText().isBlank() || tfDesconto.getText().isEmpty()){
            tfDesconto.requestFocus();
            JOptionPane.showMessageDialog(null,"Informe o desconto", "Atenção",
                    JOptionPane.WARNING_MESSAGE,null);
            throw new ValidacaoException("Informe o Desconto");
        }
        if(tfQtd.getText().equals("0")){
            tfQtd.requestFocus();
            JOptionPane.showMessageDialog(null,"Informe a Quantidade", "Atenção",
                    JOptionPane.WARNING_MESSAGE,null);
            throw new ValidacaoException("Informe mais de 0 quantidade!");
        }
        if(tfValorUnitario.getText().equals("0")){
            tfValorUnitario.requestFocus();
            JOptionPane.showMessageDialog(null,"Informe o valor", "Atenção",
                    JOptionPane.WARNING_MESSAGE,null);
            throw new ValidacaoException("Informe um valor!");
        }
    }

    private void atualizarValorPadrão() {
        produto = null;
        tfDesconto.setText("0");
        tfQtd.setText("0");
        tfValorUnitario.setText("0");
        tfVlrTotalProd.setText("0");
        tfProduto.setText("");
    }

    private void atualizarDesconto(double vlrDesconto) {
        double vlrTotal=0; 
        
        for(int i = 0; i<listaProdutos.size(); i++){
            vlrTotal += (listaProdutos.get(i).getVlUnit()) * (listaProdutos.get(i).getQtd());

        }
        vlrTotal = vlrTotal - vlrDesconto;
        tfVlrTotal.setText(String.valueOf(vlrTotal));
    }
}
